---
- hosts: node01
  gather_facts: false
  tasks:
    - name: Run kubeadm init
      command: "kubeadm init --experimental-upload-certs --apiserver-advertise-address={{ ansible_host }} --pod-network-cidr=10.0.0.0/16"
      args:
        creates: /etc/kubernetes/admin.conf
      register: output

    - debug:
        var: output

    - name: Copy kube conf to localhost
      fetch:
        src: /etc/kubernetes/admin.conf
        dest: "{{ playbook_dir }}/"
        flat: true

    - name: Create a Deployment by reading the definition from a local file
      k8s:
        kubeconfig: "{{ playbook_dir }}/admin.conf"
        src: files/kube-router.yml
        state: present
      delegate_to: localhost

    - name: Cleanup kube-proxy deamonset
      k8s:
        kubeconfig: "{{ playbook_dir }}/admin.conf"
        name: kube-proxy
        api_version: v1
        kind: DaemonSet
        namespace: kube-system
        state: absent
      delegate_to: localhost

# TODO: Rewirte to crictl
#    - name: Cleanup kube-proxy
#      command: docker run --privileged -v /lib/modules:/lib/modules --net=host k8s.gcr.io/kube-proxy-amd64:v1.10.2 kube-proxy --cleanup

    - name: Make node schedualable when configured as worker
      command: "kubectl --kube-config={{ playbook_dir }}/admin.conf taint nodes --all node-role.kubernetes.io/master-"
      when: "'kube-node' in group_names"
      delegate_to: localhost
