- hosts: all
  become: true
  pre_tasks:
    - hostname:
        name: "{{ inventory_hostname }}"

    # Purge some after refactor of role
    - apt:
        name:
          - containerd
          - kubelet
        state: absent
        purge: true
    - file:
        path: "{{ item }}"
        state: absent
      loop:
        - /opt/cni/bin/
        - /etc/cni/net.d/

  roles:
    - ../arm64-containerd-kubernetes
