---
- hosts: all
  gather_facts: false
  become: true
  tasks:
    - name: Reset with kubeadm
      command: kubeadm reset -f
      register: output

    - name: Echo output
      debug:
        var: output

    - name: Reset iptables
      shell: "iptables -F && iptables -t nat -F && iptables -t mangle -F && iptables -X"
      register: output

    - name: Echo output
      debug:
        var: output

    - name: Remove ansible init file
      file:
        path: /etc/kubernetes/.ansible_init
        state: absent

    - name: Reset ipvs
      command: ipvsadm --clear
      register: output

    - name: Echo output
      debug:
        var: output

#    - name: Delete node when not the whole cluster is reset
#      command: "kubectl --kubeconfig={{ playbook_dir }}/admin.conf delete node {{ inventory_hostname }}"
#      delegate_to: localhost

