---
- block:
  - name: Add gpg key for Docker
    apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg
      state: present

  - name: Add Docker source list
    apt_repository:
      repo: "deb [arch={{ host_architecture }}] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
      state: present
      filename: docker

  - name: Install containerd
    apt:
      name: "containerd.io={{ containerd_version }}"
      state: present
      update_cache: true
    notify: restart containerd

  - name: Set containerd as hold
    dpkg_selections:
      name: containerd.io
      selection: hold

  when: ansible_distribution == 'Ubuntu'

- block:
  - name: Add docker yum repository
    yum_repository:
      name: docker-ce-stable
      description: "Docker CE Stable - {{ ansible_architecture }}"
      baseurl: "https://download.docker.com/linux/centos/7/{{ ansible_architecture }}/stable"
      enabled: true
      gpgcheck: true
      gpgkey: "https://download.docker.com/linux/centos/gpg"
      includepkgs: containerd.io

  - name: Install containerd
    yum:
      name:
        - libseccomp
        - "containerd.io-{{ containerd_version }}"
      state: present
    notify: restart containerd

  when: ansible_distribution == 'CentOS'

- name: Create a directory for containerd config
  file:
    path: /etc/containerd
    state: directory

- name: Set config to file
  copy:
    src: containerd.toml
    dest: /etc/containerd/config.toml
  notify: restart containerd

- name: Enable Containerd
  systemd:
    name: containerd
    enabled: true

- name: Create crictl config
  copy:
    content: "runtime-endpoint: unix:///run/containerd/containerd.sock"
    dest: /etc/crictl.yaml
    group: root
    owner: root
