---
# Disable swap
- name: swap - remove current swaps from fstab
  lineinfile:
    dest: /etc/fstab
    regexp: '^/[\S]+\s+none\s+swap '
    state: absent

- name: see of there are active swap devices or files
  shell: "cat /proc/swaps | wc -l"
  register: active_swaps
  changed_when: false

- name: Disable swap
  command: swapoff -a
  changed_when: false
  when: active_swaps.stdout|int > 1

# See https://kubernetes.io/docs/setup/cri/#containerd
- name: Load needed kernel modules
  modprobe:
    name: "{{ item }}"
    state: present
  loop: "{{ needed_kernel_modules }}"

- name: Make sure kernel modules are loaded on reboot
  lineinfile:
    path: /etc/modules-load.d/modules.conf
    line: "{{ item }}"
    create: true
  loop: "{{ needed_kernel_modules }}"

- name: Set sysctl parameters
  sysctl:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
  loop: "{{ needed_sysctl_parameters }}"

- block:
  - name: Add gpg key for Kubernetes
    apt_key:
      url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
      state: present

  # TODO: Replace xenial with just distri release when bionic released in https://packages.cloud.google.com/apt/dists
  - name: Add kubernetes source list
    apt_repository:
      repo: "deb http://apt.kubernetes.io/ kubernetes-{{ ansible_distribution_release | replace('bionic', 'xenial') }} main"
      state: present
      filename: kubernetes

  - name: Install kubeadm, kubectl, kubelet, kubernetes-cni
    apt:
      name:
        - "kubeadm={{ kubernetes_version }}-00"
        - "kubectl={{ kubernetes_version }}-00"
        - "kubelet={{ kubernetes_version }}-00"
        - "kubernetes-cni={{ kubernetes_cni_version }}-00"
      state: present
      update_cache: true

  - name: Set kubeadm, kubectl, kubelet as hold
    dpkg_selections:
      name: "{{ item }}"
      selection: hold
    loop:
      - kubeadm
      - kubectl
      - kubelet
      - kubernetes-cni

  when: ansible_distribution == 'Ubuntu'

- block:
  - name: Kubernetes yum add repository
    yum_repository:
      name: kubernetes
      description: "Kubernetes - {{ ansible_architecture }}"
      baseurl: "https://packages.cloud.google.com/yum/repos/kubernetes-el7-{{ ansible_architecture }}"
      enabled: true
      gpgcheck: true
      repo_gpgcheck: true
      gpgkey:
        - "https://packages.cloud.google.com/yum/doc/yum-key.gpg"
        - "https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg"

  - name: Install kubeadm, kubectl, kubelet, kubernetes-cni
    yum:
      name:
        - "kubeadm-{{ kubernetes_version }}"
        - "kubectl-{{ kubernetes_version }}"
        - "kubelet-{{ kubernetes_version }}"
        - "kubernetes-cni-{{ kubernetes_version }}"
        - "cri-tools-{{ crictl_version }}"
      state: present

  when: ansible_distribution == 'CentOS'

- name: Enable kubelet
  systemd:
    name: kubelet
    enabled: true
