---
# Lended from kubespray https://github.com/kubernetes-sigs/kubespray/blob/master/roles/etcd/tasks/main.yml#L8
- name: ansible_architecture_rename
  set_fact:
    host_architecture: >-
      {%- if ansible_architecture in architecture_groups -%}
        {{ architecture_groups[ansible_architecture] }}
      {%- else -%}
        {{ ansible_architecture }}
      {% endif %}

- name: Install apt-transport-https for HTTPS repo's
  package:
    name:
      - apt-transport-https
      - ca-certificates
    state: present

- name: Import containerd installtion
  import_tasks: containerd.yml

- name: Import kubernetes installtion
  import_tasks: kubernetes.yml

- name: Include crictl installtion
  include_tasks: crictl.yml
  when: crictl_install

- name: Include haproxy installtion
  include_tasks: haproxy.yml
  when: haproxy_install
