---
- name: Prepull all kubeadm images
  command: kubeadm config images pull
  become: true
  changed_when: false

- name: Create join command
  command: kubeadm token create --ttl 15m --print-join-command
  delegate_to: "{{ command_node }}"
  become: true
  run_once: true
  register: join_command

# Needed until https://github.com/kubernetes/kubernetes/pull/75224 is followed up
- name: Get certificate key when joining a master
  command: kubeadm init phase upload-certs --experimental-upload-certs
  delegate_to: "{{ command_node }}"
  when: "'kubemaster' in group_names"
  become: true
  run_once: true
  register: certificate_key

- name: Join node to cluster
  command: "{{ join_command.stdout }} {{ is_master | ternary(append_master_join, '') }}"
  become: true
  vars:
    is_master: "{{ 'kubemaster' in group_names }}"
    # Default is needed since the register is skipped for non master nodes but still evaluated by Ansible
    append_master_join: "--experimental-control-plane --certificate-key {{ certificate_key.stdout_lines[2] | default('') }}"

- name: Set node to initialized since kubeadm has completed succesfully
  file:
    path: /etc/kubernetes/.ansible_init
    state: touch

- name: Label node as worker
  command: "kubectl --kubeconfig /etc/kubernetes/admin.conf label node {{ inventory_hostname }} {{ label }}"
  when: "'kubenode' in group_names"
  vars:
    label: node-role.kubernetes.io/worker=worker  # Needed for escaping equals and dots
